# Generated by Django 4.0.3 on 2022-04-25 00:50

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_anuncio_id_alter_clase_id_alter_entrega_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='cuerpo',
            new_name='respuesta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respondida',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_creacion',
            field=models.DateField(default=main.models.today),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_creacion',
            field=models.DateField(default=main.models.today),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateField(default=main.models.today),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_creacion',
            field=models.DateField(default=main.models.today),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
