on:
  push:
    branches:
      - master

name: Build and Deploy Backend
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: backend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  

    - name: Authorize Docker push
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

    - name: Build and Push Container
      run: |-
        docker build -t southamerica-east1-docker/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} ./.docker/Dockerfile.backend
        docker push southamerica-east1-docker/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        image: southamerica-east1-docker/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        region: ${{ env.REGION }}
        secrets: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}

# TODO run migrations

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}


# https://www.youtube.com/watch?v=6dLHcnlPi_U